"""refactor: renamed seed user name

Revision ID: 1078ce6cf1c8
Revises: 3666b3c45826
Create Date: 2024-03-28 11:16:04.271248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1078ce6cf1c8'
down_revision = '3666b3c45826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_usernames',
    sa.Column('search_id', sa.String(length=50), nullable=True),
    sa.Column('username_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('SEED', 'FOUND', name='usernametype'), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], )
    )
    op.drop_table('seed_usernames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_usernames',
    sa.Column('search_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('username_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.ENUM('SEED', 'FOUND'), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_results.id'], name='seed_usernames_ibfk_1'),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], name='seed_usernames_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('search_usernames')
    # ### end Alembic commands ###
