"""refactor: Changed username to non unique

Revision ID: 2d4b62e5eaba
Revises: 39aa7993c914
Create Date: 2024-04-04 13:32:07.550880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4b62e5eaba'
down_revision = '39aa7993c914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('username', schema=None) as batch_op:
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('username', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
