"""fix: Foreign key interdependecy

Revision ID: 31cabbc1b34e
Revises: 439ae76427a9
Create Date: 2024-03-29 09:45:04.882105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31cabbc1b34e'
down_revision = '439ae76427a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.drop_constraint('user_usage_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key('user_usage_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
