"""refactor: Added username type to many to many

Revision ID: 3666b3c45826
Revises: d69f9db963e1
Create Date: 2024-03-28 11:14:01.408665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3666b3c45826'
down_revision = 'd69f9db963e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed_usernames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('SEED', 'FOUND', name='usernametype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed_usernames', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
