"""feat: Increased length for type in username

Revision ID: 39aa7993c914
Revises: d3df21070fd4
Create Date: 2024-04-04 13:29:00.982861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39aa7993c914'
down_revision = 'd3df21070fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('username', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('username', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
