"""refactor: Changed some fields to nullable for debugging only

Revision ID: 3a3631c8bc88
Revises: 31cabbc1b34e
Create Date: 2024-03-29 10:28:22.314838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a3631c8bc88'
down_revision = '31cabbc1b34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password_reset_token',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password_salt',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('api_key',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('api_key',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_salt',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_reset_token',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('verification_token',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
