"""refactor: Made some not common to all types of search result parameter fields nullable

Revision ID: 5289e420251a
Revises: 6af4f2ee7e25
Create Date: 2024-04-27 11:49:33.061351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5289e420251a'
down_revision = '6af4f2ee7e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_result', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('handle',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('social_media',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_result', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('social_media',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('handle',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
