"""refactor: Added missing fields to the Search result

The search result was missing some important fields found in the data but not in the database. These fields are added by updating the 'username' collection to a 'user_result' collection and using this to keep record of each entry in a search result.

Revision ID: 6af4f2ee7e25
Revises: 3292a1bedfac
Create Date: 2024-04-25 18:11:03.192232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6af4f2ee7e25'
down_revision = '3292a1bedfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_result',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=256), nullable=False),
    sa.Column('social_media', sa.String(length=256), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_user_results',
    sa.Column('search_id', sa.String(length=50), nullable=False),
    sa.Column('user_result_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('SEED', 'FOUND', name='usernametype'), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_result.id'], ),
    sa.ForeignKeyConstraint(['user_result_id'], ['user_result.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'user_result_id')
    )
    op.drop_table('search_usernames')
    op.drop_table('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('search_usernames',
    sa.Column('search_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type', mysql.ENUM('SEED', 'FOUND'), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_result.id'], name='search_usernames_ibfk_1'),
    sa.ForeignKeyConstraint(['username_id'], ['username.id'], name='search_usernames_ibfk_2'),
    sa.PrimaryKeyConstraint('search_id', 'username_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('search_user_results')
    op.drop_table('user_result')
    # ### end Alembic commands ###
