"""feat: Added many to many tables

Revision ID: bebb7fac1607
Revises: b5eb84a61fe0
Create Date: 2024-03-28 11:01:47.503468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebb7fac1607'
down_revision = 'b5eb84a61fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_usernames',
    sa.Column('search_id', sa.String(length=50), nullable=True),
    sa.Column('username_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], )
    )
    op.create_table('seed_usernames',
    sa.Column('search_id', sa.String(length=50), nullable=True),
    sa.Column('username_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_results.id'], ),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_usernames')
    op.drop_table('found_usernames')
    # ### end Alembic commands ###
