"""refactor: Added username type to many to many

Revision ID: d69f9db963e1
Revises: bebb7fac1607
Create Date: 2024-03-28 11:08:45.213686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd69f9db963e1'
down_revision = 'bebb7fac1607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('found_usernames')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_usernames',
    sa.Column('search_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('username_id', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_results.id'], name='found_usernames_ibfk_1'),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], name='found_usernames_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
